name: Release & Publish

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
  CACHE_NAME: cache-node-modules
  RELEASE_BODY: 'Please refer to [CHANGELOG.md](https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/blob/master/CHANGELOG.md) for details.'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@main
        with:
          path: ./.yarn
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME  }}-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.CACHE_NAME  }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Create .yarn file
        continue-on-error: true
        run: |
          if [ ! -d "./.yarn" ]; then
            mkdir "./.yarn"
          fi

      - name: Install & Build
        run: |
          yarn install
          yarn build

  release:
    permissions:
      contents: write

    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Release for Tag
        id: release_tag
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: ${{ env.RELEASE_BODY }}

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@main
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          node --version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}