name: Release & Publish

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
  CACHE_NAME: cache-node-modules
  RELEASE_BODY: 'Please refer to [CHANGELOG.md](https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/blob/master/CHANGELOG.md) for details.'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Delete tag on failure
        if: failure()
        run: git push --delete origin ${{ github.ref }}

  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Create Release for Tag
        id: release_tag
        uses: actions/create-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          body: ${{ env.RELEASE_BODY }}
